import Main from '@/components/Main';
import About from '@/components/About';
import ContactUs from '@/components/ContactUs';
import Skill from '@/components/Skills';
import Navbar from '@/components/Navbar';
import Head from 'next/head';
import Projects from '@/components/Projects';
import Footer from '@/components/Footer';

export default function Home() {
	return (
		<>
			<Head>
				<title>Sunny Sahsi | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Main />
			<Skill />
			<Projects />
			<About />
			<ContactUs />
			<Footer />
		</>
	);
}
